name: Java CI with Maven and Checkstyle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and run Checkstyle
      run: mvn clean verify checkstyle:checkstyle

    - name: Upload Checkstyle Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-report
        path: target/checkstyle-result.xml
